print("Hello world I'm Hazem and i work as IT system engineer ^^ ")
print("Hello world")                          print("Hello world")

print("Hello world")                            print("Hello world")

print("Hello world")
print("Hello world")
print("Hello world")
print("Hello world")
print("Hello world")
print("Hello world")
print("Hello world")
print("Hello world")
print("Hello world")
print("Hello world")
print("Hello world")
print("Hello world")
print("Hello world")
print("Hello world")
print("Hello world")
print("Hello world")
print("Hello world")
print("Hello world")
print("Hello world")
print("Hello world")
print("Hello world")
print("Hello world")
print("Hello world")
print("Hello world I'm Hazem and i work as IT system engineer ^^ ")
